spring:
    application:
        name: clean-arch
    h2:
        console:
            enabled: true
    datasource:
        url: jdbc:h2:mem:testdb
        username: admin
        password: admin
    jpa:
        show-sql: true
        generate-ddl: true
        properties:
            hibernate:
                format_sql: true

